### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Andreozzo77** [kenygamer/CEShopGUI#1]
crashes when i put a enchant on my weapon or item

**Comment by kenygamer** [comment]
The [issue template](https://github.com/kenygamer/CEShopGUI/blob/master/.github/ISSUE_TEMPLATE.md) is there for a reason. If you blank out the required fields it is impossible to help you. Closing for now.

**Comment by kenygamer** [comment]
The [issue template](https://github.com/kenygamer/CEShopGUI/blob/master/.github/ISSUE_TEMPLATE.md) is there for a reason. If you blank out the required fields it is impossible to help you.
